version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    expose:
      - "80"
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.8.3
    container_name: artifactory
    expose:
      - 8081
    ports:
      - 8081
    volumes:
      - /data/artifactory:/var/opt/jfrog/artifactory
    environment:
      - VIRTUAL_HOST=artifactory.local
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    expose:
      - 8080
    ports:
      - 50000:50000
    volumes:
      - /data/jenkins:/var/jenkins_home
    environment:
      - VIRTUAL_HOST=jenkins.local
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
